#!/bin/bash

################################################################################
# Terraform Apply Script
# Creates all AWS infrastructure using Terraform
#
# This script:
# 1. Validates Terraform configuration
# 2. Creates execution plan
# 3. Applies infrastructure changes
# 4. Exports outputs to deployment-info.txt
################################################################################

set -e  # Exit on any error

# Script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TERRAFORM_DIR="${SCRIPT_DIR}/terraform"
DEPLOYMENT_INFO="${SCRIPT_DIR}/deployment-info.txt"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
    echo -e "\n${BLUE}============================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}============================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${CYAN}ℹ️  $1${NC}"
}

# Main header
echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════╗"
echo "║   Terraform Apply - Create Infrastructure            ║"
echo "║   Phase 2: Deploy All AWS Resources                  ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo -e "${NC}\n"

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"
    
    # Check Terraform
    if ! command -v terraform &> /dev/null; then
        print_error "Terraform not found. Please install it first."
        exit 1
    fi
    print_success "Terraform installed"
    
    # Check if Terraform is initialized
    if [ ! -d "${TERRAFORM_DIR}/.terraform" ]; then
        print_error "Terraform not initialized. Run ./01-terraform-init.sh first."
        exit 1
    fi
    print_success "Terraform initialized"
    
    # Check AWS credentials
    if ! aws sts get-caller-identity &> /dev/null; then
        print_error "AWS credentials not configured."
        exit 1
    fi
    print_success "AWS credentials configured"
}

# Validate Terraform configuration
validate_terraform() {
    print_header "Validating Terraform Configuration"
    
    cd "$TERRAFORM_DIR"
    
    print_info "Running terraform validate..."
    if terraform validate; then
        print_success "Configuration is valid"
    else
        print_error "Configuration validation failed"
        exit 1
    fi
    
    cd "$SCRIPT_DIR"
}

# Create Terraform plan
create_plan() {
    print_header "Creating Terraform Execution Plan"
    
    cd "$TERRAFORM_DIR"
    
    print_info "Running terraform plan..."
    terraform plan -out=tfplan
    
    print_success "Execution plan created"
    
    cd "$SCRIPT_DIR"
}

# Apply Terraform plan
apply_plan() {
    print_header "Applying Terraform Plan"
    
    cd "$TERRAFORM_DIR"
    
    print_warning "This will create AWS resources that may incur costs."
    echo ""
    read -p "Do you want to continue? (yes/no): " CONFIRM
    
    if [ "$CONFIRM" != "yes" ]; then
        print_info "Terraform apply cancelled"
        rm -f tfplan
        exit 0
    fi
    
    print_info "Applying infrastructure changes..."
    terraform apply tfplan
    
    # Clean up plan file
    rm -f tfplan
    
    print_success "Infrastructure created successfully"
    
    cd "$SCRIPT_DIR"
}

# Export outputs to deployment-info.txt
export_outputs() {
    print_header "Exporting Terraform Outputs"
    
    cd "$TERRAFORM_DIR"
    
    print_info "Generating deployment-info.txt..."
    
    # Create deployment-info.txt header
    cat > "$DEPLOYMENT_INFO" << 'EOF'
#!/bin/bash
################################################################################
# Deployment Information
# Auto-generated by Terraform - DO NOT EDIT MANUALLY
# Source variables with: source deployment-info.txt
################################################################################

EOF
    
    # Export all Terraform outputs as environment variables
    echo "# General Configuration" >> "$DEPLOYMENT_INFO"
    echo "export REGION=\"$(terraform output -raw aws_region)\"" >> "$DEPLOYMENT_INFO"
    echo "export AWS_ACCOUNT_ID=\"$(terraform output -raw aws_account_id)\"" >> "$DEPLOYMENT_INFO"
    echo "export PROJECT_NAME=\"$(terraform output -raw project_name)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    echo "# VPC Configuration" >> "$DEPLOYMENT_INFO"
    echo "export VPC_ID=\"$(terraform output -raw vpc_id)\"" >> "$DEPLOYMENT_INFO"
    echo "export PUBLIC_SUBNET_ID=\"$(terraform output -raw public_subnet_id)\"" >> "$DEPLOYMENT_INFO"
    echo "export SECURITY_GROUP_ID=\"$(terraform output -raw security_group_id)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    echo "# IAM Configuration" >> "$DEPLOYMENT_INFO"
    echo "export IAM_ROLE_NAME=\"$(terraform output -raw iam_role_name)\"" >> "$DEPLOYMENT_INFO"
    echo "export IAM_INSTANCE_PROFILE_NAME=\"$(terraform output -raw iam_instance_profile_name)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    echo "# EC2 Instances" >> "$DEPLOYMENT_INFO"
    echo "export MASTER_INSTANCE_ID=\"$(terraform output -raw master_instance_id)\"" >> "$DEPLOYMENT_INFO"
    echo "export MASTER_PUBLIC_IP=\"$(terraform output -raw master_public_ip)\"" >> "$DEPLOYMENT_INFO"
    echo "export MASTER_PRIVATE_IP=\"$(terraform output -raw master_private_ip)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    echo "export WORKER1_INSTANCE_ID=\"$(terraform output -raw worker1_instance_id)\"" >> "$DEPLOYMENT_INFO"
    echo "export WORKER1_PUBLIC_IP=\"$(terraform output -raw worker1_public_ip)\"" >> "$DEPLOYMENT_INFO"
    echo "export WORKER1_PRIVATE_IP=\"$(terraform output -raw worker1_private_ip)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    echo "export WORKER2_INSTANCE_ID=\"$(terraform output -raw worker2_instance_id)\"" >> "$DEPLOYMENT_INFO"
    echo "export WORKER2_PUBLIC_IP=\"$(terraform output -raw worker2_public_ip)\"" >> "$DEPLOYMENT_INFO"
    echo "export WORKER2_PRIVATE_IP=\"$(terraform output -raw worker2_private_ip)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    echo "# SSH Configuration" >> "$DEPLOYMENT_INFO"
    echo "export KEY_NAME=\"$(terraform output -raw key_name)\"" >> "$DEPLOYMENT_INFO"
    echo "export KEY_FILE=\"$(terraform output -raw key_file)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    echo "# ECR Configuration" >> "$DEPLOYMENT_INFO"
    echo "export ECR_REGISTRY=\"$(terraform output -raw ecr_registry_url)\"" >> "$DEPLOYMENT_INFO"
    echo "export ECR_UI_REPO=\"$(terraform output -raw ecr_ui_repo)\"" >> "$DEPLOYMENT_INFO"
    echo "export ECR_CATALOG_REPO=\"$(terraform output -raw ecr_catalog_repo)\"" >> "$DEPLOYMENT_INFO"
    echo "export ECR_CART_REPO=\"$(terraform output -raw ecr_cart_repo)\"" >> "$DEPLOYMENT_INFO"
    echo "export ECR_ORDERS_REPO=\"$(terraform output -raw ecr_orders_repo)\"" >> "$DEPLOYMENT_INFO"
    echo "export ECR_CHECKOUT_REPO=\"$(terraform output -raw ecr_checkout_repo)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    echo "# DynamoDB Configuration" >> "$DEPLOYMENT_INFO"
    echo "export DYNAMODB_TABLE_NAME=\"$(terraform output -raw dynamodb_table_name)\"" >> "$DEPLOYMENT_INFO"
    echo "" >> "$DEPLOYMENT_INFO"
    
    print_success "deployment-info.txt created"
    
    # Make it executable
    chmod +x "$DEPLOYMENT_INFO"
    
    cd "$SCRIPT_DIR"
}

# Print summary
print_summary() {
    print_header "Infrastructure Deployment Complete!"
    
    # Source the deployment info
    source "$DEPLOYMENT_INFO"
    
    echo -e "${GREEN}✅ All AWS resources created successfully!${NC}"
    echo ""
    echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  Resource Summary                                       ${NC}"
    echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${CYAN}VPC & Networking:${NC}"
    echo -e "  VPC ID:            ${VPC_ID}"
    echo -e "  Subnet ID:         ${PUBLIC_SUBNET_ID}"
    echo -e "  Security Group:    ${SECURITY_GROUP_ID}"
    echo ""
    echo -e "${CYAN}EC2 Instances:${NC}"
    echo -e "  Master Node:       ${MASTER_PUBLIC_IP}"
    echo -e "  Worker Node 1:     ${WORKER1_PUBLIC_IP}"
    echo -e "  Worker Node 2:     ${WORKER2_PUBLIC_IP}"
    echo ""
    echo -e "${CYAN}ECR Registry:${NC}"
    echo -e "  ${ECR_REGISTRY}"
    echo ""
    echo -e "${CYAN}DynamoDB Table:${NC}"
    echo -e "  ${DYNAMODB_TABLE_NAME}"
    echo ""
    echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${YELLOW}⚠️  Important Notes:${NC}"
    echo "  • EC2 instances are starting up (wait 2-3 minutes)"
    echo "  • SSH key: ${KEY_FILE}"
    echo "  • All variables saved to: deployment-info.txt"
    echo ""
    echo -e "${BLUE}Next Steps:${NC}"
    echo "  1. Load environment variables:"
    echo -e "     ${CYAN}source deployment-info.txt${NC}"
    echo ""
    echo "  2. Test SSH connection (wait 2-3 minutes first):"
    echo -e "     ${CYAN}ssh -i \${KEY_FILE} ubuntu@\${MASTER_PUBLIC_IP}${NC}"
    echo ""
    echo "  3. Initialize Kubernetes cluster:"
    echo -e "     ${CYAN}./03-k8s-init.sh${NC}"
    echo ""
    echo -e "${BLUE}Useful Commands:${NC}"
    echo "  • View infrastructure: terraform -chdir=terraform show"
    echo "  • View outputs:        terraform -chdir=terraform output"
    echo "  • Destroy all:         ./99-cleanup.sh"
}

# Main execution
main() {
    check_prerequisites
    validate_terraform
    create_plan
    apply_plan
    export_outputs
    print_summary
    
    echo -e "\n${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║    Infrastructure Deployment Completed! 🎉            ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}\n"
}

# Run main function
main
