---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cart.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.cart.name }}
spec:
  replicas: {{ .Values.cart.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.cart.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cart.name }}
    spec:
      # imagePullSecrets removed - using ECR Credential Helper
      containers:
      - name: {{ .Values.cart.name }}
        image: "{{ .Values.global.ecr.registry }}/{{ .Values.cart.image.repository }}:{{ .Values.cart.image.tag }}"
        imagePullPolicy: {{ .Values.cart.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.cart.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.cart.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.global.dynamodb.tableName }}
        - name: CARTS_DYNAMODB_TABLENAME
          value: {{ .Values.global.dynamodb.tableName | quote }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.global.dynamodb.region | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.cart.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.cart.service.targetPort }}
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.cart.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cart.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.cart.name }}
spec:
  type: {{ .Values.cart.service.type }}
  ports:
  - port: {{ .Values.cart.service.port }}
    targetPort: {{ .Values.cart.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.cart.name }}
