---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.catalog.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.catalog.name }}
spec:
  replicas: {{ .Values.catalog.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.catalog.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.catalog.name }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: {{ .Values.catalog.name }}
        image: "{{ .Values.global.ecr.registry }}/{{ .Values.catalog.image.repository }}:{{ .Values.catalog.image.tag }}"
        imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.catalog.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.catalog.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.catalog.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalog.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalog.service.targetPort }}
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.catalog.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.catalog.name }}
spec:
  type: {{ .Values.catalog.service.type }}
  ports:
  - port: {{ .Values.catalog.service.port }}
    targetPort: {{ .Values.catalog.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.catalog.name }}
